### ISSUE TITLE
HR live 5 sec update vs HR?

### ISSUE THREAD

**Issue by ahdee** [warmsound/crystal-face#156]
Hi I notice that there is a choice in Heart Rate display.  I would prefer the 5 sec realtime update but would that take up more of the battery OR is the watch already collecting live ( ~ 5 sec ) anyway and this app is just displaying the data? 
thanks! 
A

**Comment by warmsound** [comment]
The 5 sec option will take up more battery, but not because of more frequent recording (the watch may do this anyway, regardless of the watchface setting), but because of larger screen updates: updating seconds alone takes less power than updating seconds and HR. This is why I've chosen to limit the live HR updates to 5 sec, rather than every second. Hope this helps.
