### ISSUE TITLE
Massive Battery drain on Vivoactive 4

### ISSUE THREAD

**Issue by marco123445** [warmsound/crystal-face#181]
The Battery drain on my Vivoactive 4 is massive since a recent update

**Comment by LibertyBeta** [comment]
I'm seeing similar drain on my VA4 as well as the Infocal face, which uses a lot of the same code.

**Comment by mkuthan** [comment]
The same for Vivoactive 3, version 2.4.3. Unfortunately I don't know previously installed version.

**Comment by zigford** [comment]
Same here. Any logs I can gather to help? Love the crystal watch face

**Comment by warmsound** [comment]
Hi guys, thanks for reporting this issue, and sorry for the slow reply. I have a VA3, and I'm monitoring the behaviour on my watch. A few initial questions:

- Roughly what is the rate of battery drain (e.g. % per hour, or % per day)?
- Did you uninstall any previous version, before installing the new one?
- What settings changes have you made, if any? In particular, are you using the "Heart Rate (Live 5s)" data field?

Thanks for your support and help,

Vince.

**Comment by LibertyBeta** [comment]
Garmine forerunner 245 and a (now returned) VA4. New clean installs. Stock settings. 

Saw around 2-4% hourly drain verses 0.5% on stock watchface.

**Comment by warmsound** [comment]
@LibertyBeta After a fresh install on my watch, battery dropped 4-5% within the first hour, but then stabilised to the usual ~0.5% per hour. I assume your high hourly drain is continuous?

**Comment by zigford** [comment]
I'll do an overnight test with mine on stock settings. I got my VA4 new earlier this month, so I think I installed crystal fresh and hadn't gone through the watchface update.

**Comment by LibertyBeta** [comment]
@warmsound Yeah, drain never normalized back down to ~.5%. Checked overnight as well, same. Rough drainage stats. I charge on Fridays, so I can test again end of week if that helps.

**Comment by zigford** [comment]
Overnight with stock setting it worked fine at .5% battery drain per hour. Which heart rate setting affects battery life more the normal one or the live (5s) one?

**Comment by warmsound** [comment]
My VA3, firmware 7.40, Crystal 2.4.5, has lasted just over a week before needing a charge, so I haven't been able to reproduce the problem.

However, I've found [this thread](https://forums.garmin.com/sports-fitness/healthandwellness/f/vivoactive-3-3-music/234120/vivoactive-3-sw-7-40-is-live) for the VA3 7.40 firmware where high battery drain is reported generally (e.g. dead in 10 hours), so it's possible that the firmware, rather than Crystal, is the root cause. High battery drain also reported on [this thread](https://forums.garmin.com/sports-fitness/healthandwellness/f/vivoactive-4-series/238197/vivoactive-4-all-versions-sw-5-10) for the latest VA4 5.10 firmware.

What firmware is everyone running?

It would be interesting to know why only some users experience the issue, and whether a watch face can do anything to make the problem worse.

@zigford the Live (5s) HR setting will drain the battery more. The difference is in low power mode: assuming you're showing seconds, the regular HR setting doesn't update the screen at all, so only the seconds need to be drawn each second. With the 5s setting, every 5th second, both the HR figure/dot and the seconds need to be drawn. The CPU time required to update the screen is related* to the area of a box that encloses all elements that need to be updated, so every 5th second, there's a bump in the CPU time required. So the 5s HR value (as opposed to e.g. every second) was chosen as a compromise. In any case, CIQ has a hard limit of 30ms per frame, averaged over a minute. Crystal takes ~5ms per frame on VA3, with Live (5s) taking ~31ms every 5th frame. (*vague here, as I used to think the CPU time was directly proportional to the area of the enclosing box, but that no longer seems to be the case.) Probably more info than you wanted... 🤓

**Comment by zigford** [comment]
Thanks @warmsound for the detailed info. I’m starting to think the problem is for all third party watchafaces on this firmware. I’ve found another bug that only affects third party watchfaces. The hydration reminder always crashes when accepted if a third party watch face is active. If a built-in one is used it works fine.

I’m testing drain between various other faces and so far the difference is quite dramatic when compared to the built-in ones. 

I haven’t been able to repeat my previous overnight test with crystal consuming ~.5% but I was attempting to use a light theme which I suspect uses a fair bit more power. On light red, I haven’t been able to get battery drain below 1% per hour.

**Comment by zigford** [comment]
Possibly relevant: https://forums.garmin.com/developer/connect-iq/i/bug-reports/battery-drain-issues-on-va4-and-4s-using-ciq-watch-faces-since-sw-5-10-release

**Comment by LibertyBeta** [comment]
Checked the CL for the 6.x beta for the 245. No response yet on if this CIQ
bug is fixed yet.
-- 
Rainer Paskiewicz

**Comment by mkuthan** [comment]
Some facts:
* VA3, firmware 7.40
* Crystal Face 2.4.3, 2.4.5 - battery drain ~10% / h (before ~1% / h, I did not change the settings)
* Simply Late watch face (latest) ~ 1% / h

**Comment by zigford** [comment]
New update available with note
> Fixed some scenarios where battery drain can occur on Connect IQ watch faces

my gut feel is it’s related to the hydration tracking crash that happens with CIQ watchfaces.

Time will tell.

https://forums.garmin.com/sports-fitness/healthandwellness/f/vivoactive-4-series/254026/vivoactive-4-software-update---version-5-60

**Comment by marco123445** [comment]
> New update available with note
> 
> > Fixed some scenarios where battery drain can occur on Connect IQ watch faces
> 
> my gut feel is it’s related to the hydration tracking crash that happens with CIQ watchfaces.
> 
> Time will tell.
> 
> https://forums.garmin.com/sports-fitness/healthandwellness/f/vivoactive-4-series/254026/vivoactive-4-software-update---version-5-60

**Comment by warmsound** [comment]
Thanks all for the update on this - let's hope the firmware update solves the problem 🤞
