### ISSUE TITLE
Support for Fenix 7

### ISSUE THREAD

**Issue by kmoens** [warmsound/crystal-face#214]
I would love to have support for the Garmin Fenix 7, I own a Fenix 7, so I can offer to test if you want.

**Comment by SylvainGa** [comment]
He hasn't been active since June of last year. I have changes, like Oxymetre display that are waiting to be merged to the repo since then. I tried contacting him a few times but never got an answer. I'm afraid this repo is orphan unfortunately :-(

**Comment by warmsound** [comment]
@kmoens, @SylvainGa, I've resumed supporting Crystal, and added support for Fenix 7 in version `2.6.0`, released Dec 23. Thanks for your patience, and @SylvainGa, for all your work in keeping Crystal alive in your fork.

**Comment by SylvainGa** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi! I was afraid something had happened to you. Really glad to see you're still around.Are you planning on adding Complications to the watchface? It's really convenient, especially the launching of the widgets directly from the watchfaces. You can look at how I did it if you so wish. Not sure if it was the most optimized way though as I augmented some of the fields. I added some "tagging" so older devices not supporting complications wouldn't have that code compiled since it would have meant removing them from support since the code got too big for them. It means that two code sets need to be supported, which is more work on our side however.                                                                                                                                                                                                                                                                                                                         De : ***@***.***é : 1 janvier 2024 04 h 15À : ***@***.***épondre à : ***@***.*** : ***@***.***; ***@***.*** : Re: [warmsound/crystal-face] Support for Fenix 7 (Issue #214)  
@kmoens, @SylvainGa, I've resumed supporting Crystal, and added support for Fenix 7 in version 2.6.0, released Dec 23. Thanks for your patience, and @SylvainGa, for all your work in keeping Crystal alive in your fork.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
